rasch_config: !config
  default_encoding: 'vertex'
  default_environment: '2x3x2-switch_dead_end_passing'
  asp_encodings_path: 'data/encodings/'
  asp_instances_path: 'data/instances/'
  flatland_environments_path: 'data/environments/'
  solver_output_path: 'data/solutions/'
  statistics_output_path: 'data/statistics/'
