rasch_config: !config
  default_encoding: 'vertex'
  default_environment: '2x3x2-switch_dead_end_passing'
  asp_encodings_path: 'data/encodings/'
  asp_instances_path: 'data/instances/'
  flatland_environments_path: 'data/environments/'
  solver_output_path: 'data/solutions/'
  statistics_output_path: 'data/statistics/'

rasch_horizon:
  2x3x1-simple_switch: 20
  2x3x2-switch_dead_end_passing: 20
  4x3x1-no_exit: 20
  5x5x1-snake: 25
  5x5x2-crossing: 100
  20x20x1-snake: 400
  simple_switch_map: 20